"""empty message

Revision ID: 6a24ade57e6b
Revises: 3c26c0dac573
Create Date: 2023-05-21 11:35:21.075770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a24ade57e6b'
down_revision = '3c26c0dac573'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
